# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('status', model_utils.fields.StatusField(choices=[('queued', 'queued'), ('started', 'started'), ('in progress', 'in progress'), ('complete', 'complete')], default='queued', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('is_removed', models.BooleanField(default=False)),
                ('schema', models.TextField(verbose_name='Elasticsearch Schema JSON')),
                ('version', models.CharField(max_length=64, verbose_name='Codebase Version')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IndexMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Index Name')),
                ('active_index_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_elastic_migrations.IndexInstance')),
            ],
        ),
        migrations.AddField(
            model_name='indexinstance',
            name='index_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_elastic_migrations.IndexMaster'),
        ),
        migrations.AddField(
            model_name='indexaction',
            name='index_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_elastic_migrations.IndexInstance'),
        ),
        migrations.AddField(
            model_name='indexaction',
            name='index_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_elastic_migrations.IndexMaster'),
        ),
    ]
