# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_elastic_migrations', '0002_indexaction_argv'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexaction',
            name='docs_affected',
            field=models.IntegerField(default=0),
        ),
    ]
