# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_elastic_migrations', '0003_indexaction_docs_affected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexaction',
            name='action',
            field=models.CharField(choices=[('create_index', 'create_index'), ('update_index', 'update_index'), ('activate_index', 'activate_index'),
                                            ('deactivate_index', 'deactivate_index'), ('clear_index', 'clear_index'), ('drop_index', 'drop_index')], max_length=64),
        ),
    ]
