# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_elastic_migrations', '0004_auto_20180703_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexaction',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('aborted', 'aborted')],
                                   default='queued', max_length=32),
        ),
    ]
