# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-09 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_elastic_migrations', '0005_auto_20180703_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialUpdateIndexAction',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('django_elastic_migrations.updateindexaction',),
        ),
        migrations.AddField(
            model_name='indexaction',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='django_elastic_migrations.IndexAction'),
        ),
        migrations.AddField(
            model_name='indexaction',
            name='task_kwargs',
            field=models.TextField(default='{}', verbose_name='json of kwargs to pass to action'),
        ),
        migrations.AlterField(
            model_name='indexaction',
            name='action',
            field=models.CharField(choices=[('create_index', 'create_index'), ('update_index', 'update_index'), ('activate_index', 'activate_index'),
                                            ('deactivate_index', 'deactivate_index'), ('clear_index', 'clear_index'), ('drop_index', 'drop_index'),
                                            ('partial_update_index', 'partial_update_index')], max_length=64),
        ),
    ]
