# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_elastic_migrations', '0006_auto_20180709_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeactivateIndexAction',
        ),
        migrations.AlterField(
            model_name='indexaction',
            name='action',
            field=models.CharField(choices=[('create_index', 'create_index'), ('update_index', 'update_index'), ('activate_index', 'activate_index'), ('clear_index', 'clear_index'), ('drop_index', 'drop_index'), ('partial_update_index', 'partial_update_index')], max_length=64),
        ),
    ]
