# Generated by Django 2.1.3 on 2018-11-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_elastic_migrations', '0006_auto_20180709_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeactivateIndexAction',
        ),
        migrations.AlterField(
            model_name='index',
            name='active_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_elastic_migrations.IndexVersion'),
        ),
        migrations.AlterField(
            model_name='indexaction',
            name='action',
            field=models.CharField(choices=[('create_index', 'create_index'), ('update_index', 'update_index'), ('activate_index', 'activate_index'), ('clear_index', 'clear_index'), ('drop_index', 'drop_index'), ('partial_update_index', 'partial_update_index')], max_length=64),
        ),
    ]
